version: "3.3"

services:
  api:
    image: doggo_api
    build: ./back
    networks:
      doggo-network:
    ports:
      - 8080:8080

  front:
    image: doggo_front
    build: ./front
    networks:
      doggo-network:
    ports:
      - 80:80

networks:
  doggo-network:
    driver: bridge
