version: "3.4"

networks:
  doggo-network:
    driver: bridge

x-template: &common
  restart: always
  env_file:
    - e.nv
  networks: 
    - doggo-network

services:
  #  pls, do not use db docker container in prod
  local-db:
    <<: *common
    image: postgres:12.2

  api:
    <<: *common
    image: doggo_api
    build: ./back
    depends_on:
      - local-db
    ports:
      - 8080:8080

  front:
    <<: *common
    image: doggo_front
    build: ./front
    ports:
      - 80:80

